In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
final_df = pd.read_csv("final_faers_data.csv")
final_df.head(10)

,primaryid,fda_dt,age_grp,sex,reporter_country,occr_country,age_in_years,is_hcp,drug_sequence,drug_role,...,active_chemical,route,dechallenge,dose_amount,dose_form,reaction_term,indication_for_use,outcome_code,start_dt,therapy_status
0,41627247,20201124,Adult,UNK,GB,GB,59.0,True,1,PS,...,DIDANOSINE,Transplacental,Unknown,400.0,Unknown,Brain malformation,Product used for unknown indication,Congenital Anomaly,20040122.0,Completed
1,41627247,20201124,Adult,UNK,GB,GB,59.0,True,1,PS,...,DIDANOSINE,Transplacental,Unknown,400.0,Unknown,Brain malformation,Product used for unknown indication,Other Serious,20040122.0,Completed
2,41627247,20201124,Adult,UNK,GB,GB,59.0,True,1,PS,...,DIDANOSINE,Transplacental,Unknown,400.0,Unknown,Congenital central nervous system anomaly,Product used for unknown indication,Congenital Anomaly,20040122.0,Completed
3,41627247,20201124,Adult,UNK,GB,GB,59.0,True,1,PS,...,DIDANOSINE,Transplacental,Unknown,400.0,Unknown,Congenital central nervous system anomaly,Product used for unknown indication,Other Serious,20040122.0,Completed
4,41627247,20201124,Adult,UNK,GB,GB,59.0,True,1,PS,...,DIDANOSINE,Transplacental,Unknown,400.0,Unknown,Foetal exposure during pregnancy,Product used for unknown indication,Congenital Anomaly,20040122.0,Completed
5,41627247,20201124,Adult,UNK,GB,GB,59.0,True,1,PS,...,DIDANOSINE,Transplacental,Unknown,400.0,Unknown,Foetal exposure during pregnancy,Product used for unknown indication,Other Serious,20040122.0,Completed
6,41627247,20201124,Adult,UNK,GB,GB,59.0,True,1,PS,...,DIDANOSINE,Transplacental,Unknown,400.0,Unknown,Pulmonary hypoplasia,Product used for unknown indication,Congenital Anomaly,20040122.0,Completed
7,41627247,20201124,Adult,UNK,GB,GB,59.0,True,1,PS,...,DIDANOSINE,Transplacental,Unknown,400.0,Unknown,Pulmonary hypoplasia,Product used for unknown indication,Other Serious,20040122.0,Completed
8,41627247,20201124,Adult,UNK,GB,GB,59.0,True,2,SS,...,NEVIRAPINE,Transplacental,Unknown,400.0,TABLET,Brain malformation,Product used for unknown indication,Congenital Anomaly,20000122.0,Completed
9,41627247,20201124,Adult,UNK,GB,GB,59.0,True,2,SS,...,NEVIRAPINE,Transplacental,Unknown,400.0,TABLET,Brain malformation,Product used for unknown indication,Other Serious,20000122.0,Completed

In [3]:
final_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4635053 entries, 0 to 4635052
Data columns (total 21 columns):
 #   Column              Dtype
---  ------              -----
 0   primaryid           int64
 1   fda_dt              int64
 2   age_grp             object
 3   sex                 object
 4   reporter_country    object
 5   occr_country        object
 6   age_in_years        float64
 7   is_hcp              bool
 8   drug_sequence       int64
 9   drug_role           object
 10  drugname            object
 11  active_chemical     object
 12  route               object
 13  dechallenge         object
 14  dose_amount         float64
 15  dose_form           object
 16  reaction_term       object
 17  indication_for_use  object
 18  outcome_code        object
 19  start_dt            object
 20  therapy_status      object
dtypes: bool(1), float64(2), int64(3), object(15)
memory usage: 711.7+ MB

In [4]:
final_df['outcome_code'].value_counts()

outcome_code
Other Serious            2332699
Hospitalization          1287746
Outcome Not Specified     335334
Disability                252877
Life-Threatening          224959
Death                     192225
Congenital Anomaly          8662
Required Intervention        551
Name: count, dtype: int64

In [5]:
final_df['route'].value_counts()

route
Oral                                     1606446
Unknown                                  1197802
Intravenous (not otherwise specified)     850600
Subcutaneous                              712017
Intramuscular                             111997
Intravenous drip                           62515
Transplacental                             15392
Other                                      12589
Respiratory (inhalation)                   11796
Topical                                     7947
Transdermal                                 5014
Intraocular                                 4757
Intra-uterine                               4681
Intra-arterial                              4640
Intrathecal                                 4188
Parenteral                                  3242
Sublingual                                  3096
Vaginal                                     2673
Intravenous bolus                           2519
Hemodialysis                                1539
Ophthalmic                                  1408
Urethral                                    1206
Sunconjunctival                             1068
Endocervical                                 931
Buccal                                       793
Nasal                                        766
IRRIGATION                                   525
Transmammary                                 441
Rectal                                       402
Intra-articular                              351
Subdermal                                    350
INTRACAVITY                                  269
Epidural                                     203
Intracardiac                                 177
Cutaneous                                    129
Intradermal                                   92
Intravesical                                  82
Intratumor                                    72
Intracisternal                                51
Intracavernous                                47
Oropharingeal                                 38
Intraperitoneal                               37
Occlusive dressing technique                  35
Intratracheal                                 31
Intrahepatic                                  20
Intrameningeal                                12
Intradiscal (intraspinal)                     10
INTRASINAL                                    10
Intrapleural                                   9
Endotracheal                                   6
Intracoronary                                  6
Intracervical                                  6
Intrathoracic                                  5
Retrobulbar                                    4
Intra-amniotic                                 3
Iontophoresis                                  3
Dental                                         2
Perineural                                     2
Periarticular                                  1
Name: count, dtype: int64

In [6]:
final_df['drug_role'].value_counts()

drug_role
SS    3621820
PS    1013233
Name: count, dtype: int64

In [7]:
selected_cols = [
    'primaryid',
    
    'age_grp', 
    'sex', 
    'is_hcp',
    
    'active_chemical',
    'drug_role',
    'route',
    'indication_for_use',
    'dechallenge',
    
    # Target
    'outcome_code',
    'reaction_term'
]

df_basic = final_df[selected_cols].copy()
df_basic.head(10)

,primaryid,age_grp,sex,is_hcp,active_chemical,drug_role,route,indication_for_use,dechallenge,outcome_code,reaction_term
0,41627247,Adult,UNK,True,DIDANOSINE,PS,Transplacental,Product used for unknown indication,Unknown,Congenital Anomaly,Brain malformation
1,41627247,Adult,UNK,True,DIDANOSINE,PS,Transplacental,Product used for unknown indication,Unknown,Other Serious,Brain malformation
2,41627247,Adult,UNK,True,DIDANOSINE,PS,Transplacental,Product used for unknown indication,Unknown,Congenital Anomaly,Congenital central nervous system anomaly
3,41627247,Adult,UNK,True,DIDANOSINE,PS,Transplacental,Product used for unknown indication,Unknown,Other Serious,Congenital central nervous system anomaly
4,41627247,Adult,UNK,True,DIDANOSINE,PS,Transplacental,Product used for unknown indication,Unknown,Congenital Anomaly,Foetal exposure during pregnancy
5,41627247,Adult,UNK,True,DIDANOSINE,PS,Transplacental,Product used for unknown indication,Unknown,Other Serious,Foetal exposure during pregnancy
6,41627247,Adult,UNK,True,DIDANOSINE,PS,Transplacental,Product used for unknown indication,Unknown,Congenital Anomaly,Pulmonary hypoplasia
7,41627247,Adult,UNK,True,DIDANOSINE,PS,Transplacental,Product used for unknown indication,Unknown,Other Serious,Pulmonary hypoplasia
8,41627247,Adult,UNK,True,NEVIRAPINE,SS,Transplacental,Product used for unknown indication,Unknown,Congenital Anomaly,Brain malformation
9,41627247,Adult,UNK,True,NEVIRAPINE,SS,Transplacental,Product used for unknown indication,Unknown,Other Serious,Brain malformation

In [8]:
df_basic.isnull().sum()

primaryid             0
age_grp               0
sex                   0
is_hcp                0
active_chemical       0
drug_role             0
route                 0
indication_for_use    0
dechallenge           0
outcome_code          0
reaction_term         0
dtype: int64

In [9]:
df_basic['indication_for_use'] = df_basic['indication_for_use'].replace(
    'Product used for unknown indication', 'Unknown'
)
df_basic['indication_for_use'].value_counts()

indication_for_use
Unknown                                        2767084
Rheumatoid arthritis                            393015
Crohn's disease                                  49810
Plasma cell myeloma                              44248
Asthma                                           43555
                                                ...
Hepatic encephalopathy prophylaxis                   1
Vasoactive intestinal polypeptide increased          1
Tilt table test                                      1
Central venous catheterisation                       1
Postinfarction angina                                1
Name: count, Length: 3941, dtype: int64

In [10]:
df_basic['drug_profile'] = df_basic['active_chemical'] + \
                           '_ROLE_' + df_basic['drug_role'] + \
                           '_ROUTE_' + df_basic['route'] + \
                           '_IND_' + df_basic['indication_for_use'] + \
                           '_DECHAL_' + df_basic['dechallenge']

df_basic

,primaryid,age_grp,sex,is_hcp,active_chemical,drug_role,route,indication_for_use,dechallenge,outcome_code,reaction_term,drug_profile
0,41627247,Adult,UNK,True,DIDANOSINE,PS,Transplacental,Unknown,Unknown,Congenital Anomaly,Brain malformation,DIDANOSINE_ROLE_PS_ROUTE_Transplacental_IND_Un...
1,41627247,Adult,UNK,True,DIDANOSINE,PS,Transplacental,Unknown,Unknown,Other Serious,Brain malformation,DIDANOSINE_ROLE_PS_ROUTE_Transplacental_IND_Un...
2,41627247,Adult,UNK,True,DIDANOSINE,PS,Transplacental,Unknown,Unknown,Congenital Anomaly,Congenital central nervous system anomaly,DIDANOSINE_ROLE_PS_ROUTE_Transplacental_IND_Un...
3,41627247,Adult,UNK,True,DIDANOSINE,PS,Transplacental,Unknown,Unknown,Other Serious,Congenital central nervous system anomaly,DIDANOSINE_ROLE_PS_ROUTE_Transplacental_IND_Un...
4,41627247,Adult,UNK,True,DIDANOSINE,PS,Transplacental,Unknown,Unknown,Congenital Anomaly,Foetal exposure during pregnancy,DIDANOSINE_ROLE_PS_ROUTE_Transplacental_IND_Un...
...,...,...,...,...,...,...,...,...,...,...,...,...
4635048,186954941,Adult,M,True,ETOPOSIDE,SS,Unknown,Unknown,Not applicable,Hospitalization,Pyrexia,ETOPOSIDE_ROLE_SS_ROUTE_Unknown_IND_Unknown_DE...
4635049,186954941,Adult,M,True,VINCRISTINE SULFATE,SS,Unknown,Unknown,Not applicable,Hospitalization,Neutropenia,VINCRISTINE SULFATE_ROLE_SS_ROUTE_Unknown_IND_...
4635050,186954941,Adult,M,True,VINCRISTINE SULFATE,SS,Unknown,Unknown,Not applicable,Hospitalization,Pyrexia,VINCRISTINE SULFATE_ROLE_SS_ROUTE_Unknown_IND_...
4635051,186954941,Adult,M,True,PREDNISONE,SS,Unknown,Unknown,Not applicable,Hospitalization,Neutropenia,PREDNISONE_ROLE_SS_ROUTE_Unknown_IND_Unknown_D...
4635052,186954941,Adult,M,True,PREDNISONE,SS,Unknown,Unknown,Not applicable,Hospitalization,Pyrexia,PREDNISONE_ROLE_SS_ROUTE_Unknown_IND_Unknown_D...

In [11]:
df_agg = df_basic.groupby('primaryid').agg(
    age_grp=('age_grp', 'first'),
    sex=('sex', 'first'),
    is_hcp=('is_hcp', 'first'),
    
    all_drug_profiles=('drug_profile', lambda x: list(x.unique())),
    
    all_outcomes=('outcome_code', lambda x: list(x.unique())),
    all_reactions=('reaction_term', lambda x: list(x.unique()))
)

print(f"Original rows: {len(df_basic)}, Aggregated rows: {len(df_agg)}")
df_agg.head(10)

Original rows: 4635053, Aggregated rows: 224916

,age_grp,sex,is_hcp,all_drug_profiles,all_outcomes,all_reactions
primaryid,,,,,,
41627247,Adult,UNK,True,[DIDANOSINE_ROLE_PS_ROUTE_Transplacental_IND_U...,"[Congenital Anomaly, Other Serious]","[Brain malformation, Congenital central nervou..."
42021114,Adult,F,False,[LEVOFLOXACIN_ROLE_PS_ROUTE_Unknown_IND_Pneumo...,[Death],"[Septic shock, Toxic epidermal necrolysis]"
56585445,Adult,M,True,[MYCOPHENOLIC ACID_ROLE_PS_ROUTE_Oral_IND_Rena...,"[Death, Hospitalization]","[American trypanosomiasis, Arthralgia, Bacteri..."
57528163,Adult,M,False,[ACETAMINOPHEN_ROLE_PS_ROUTE_Unknown_IND_Pyrex...,[Hospitalization],"[Blood sodium increased, Hypernatraemia, Overd..."
62923272,Elderly,F,False,[GABAPENTIN_ROLE_PS_ROUTE_Unknown_IND_Analgesi...,[Hospitalization],"[Agitation, Drug abuse, Exophthalmos, Hyperhid..."
63657203,Elderly,F,False,[OXYCODONE HYDROCHLORIDE_ROLE_PS_ROUTE_Oral_IN...,"[Death, Other Serious]","[Anxiety, Asphyxia, Cerebrovascular accident, ..."
63716933,Adult,M,False,[OXYCODONE HYDROCHLORIDE_ROLE_PS_ROUTE_Oral_IN...,"[Hospitalization, Other Serious]","[Anger, Depression, Drug dependence, Hospitali..."
63890722,Adult,M,False,[OXYCODONE HYDROCHLORIDE_ROLE_PS_ROUTE_Oral_IN...,[Other Serious],"[Abdominal pain, Drug dependence, Drug withdra..."
63926532,Adult,F,False,[OXYCODONE HYDROCHLORIDE_ROLE_PS_ROUTE_Oral_IN...,"[Other Serious, Disability]","[Constipation, Drug dependence, Drug withdrawa..."
64329942,Adult,M,False,[OXYCODONE HYDROCHLORIDE_ROLE_PS_ROUTE_Oral_IN...,[Other Serious],"[Abdominal pain upper, Aggression, Amnesia, Ch..."

In [12]:
# ['A_...', 'B_...'] -> "A_... B_..."
df_agg['drug_profile_joined'] = df_agg['all_drug_profiles'].apply(lambda x: ' '.join(x))

feature_columns = [
    'age_grp', 
    'sex', 
    'is_hcp',
    'drug_profile_joined'
]

X = df_agg[feature_columns]
X

,age_grp,sex,is_hcp,drug_profile_joined
primaryid,,,,
41627247,Adult,UNK,True,DIDANOSINE_ROLE_PS_ROUTE_Transplacental_IND_Un...
42021114,Adult,F,False,LEVOFLOXACIN_ROLE_PS_ROUTE_Unknown_IND_Pneumon...
56585445,Adult,M,True,MYCOPHENOLIC ACID_ROLE_PS_ROUTE_Oral_IND_Renal...
57528163,Adult,M,False,ACETAMINOPHEN_ROLE_PS_ROUTE_Unknown_IND_Pyrexi...
62923272,Elderly,F,False,GABAPENTIN_ROLE_PS_ROUTE_Unknown_IND_Analgesic...
...,...,...,...,...
1843672210,Elderly,F,True,LENVATINIB_ROLE_PS_ROUTE_Oral_IND_Endometrial ...
1844261710,Adult,F,False,OMEPRAZOLE_ROLE_PS_ROUTE_Unknown_IND_Dyspepsia...
1846171511,Adult,F,True,PEMBROLIZUMAB_ROLE_SS_ROUTE_Intravenous drip_I...
1846487710,Adult,M,True,ENCORAFENIB_ROLE_PS_ROUTE_Oral_IND_Malignant m...
1847450810,Adult,F,True,LENALIDOMIDE_ROLE_SS_ROUTE_Oral_IND_Unknown_DE...

In [13]:
from sklearn.preprocessing import MultiLabelBinarizer

# translate your list of text outcomes into a numeric matrix (filled with 0s and 1s)

outcome_classes = [
    'Other Serious', 'Hospitalization', 'Outcome Not Specified', 
    'Disability', 'Life-Threatening', 'Death', 
    'Congenital Anomaly', 'Required Intervention'
]

mlb_outcomes = MultiLabelBinarizer(classes=outcome_classes)

# Now for all the outcomes list in each row will be represented as list of 0 and 1 where 1 means this outcome is in the outcomes list
y_risk = mlb_outcomes.fit_transform(df_agg['all_outcomes']) 

y_risk

array([[1, 0, 0, ..., 0, 1, 0],
       [0, 0, 0, ..., 1, 0, 0],
       [0, 1, 0, ..., 1, 0, 0],
       ...,
       [0, 1, 0, ..., 0, 0, 0],
       [1, 1, 0, ..., 0, 0, 0],
       [1, 1, 0, ..., 0, 0, 0]], shape=(224916, 8))

In [14]:
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.compose import ColumnTransformer

feature_preprocessor = ColumnTransformer(
    transformers=[
        # Handle 'low' cardinality categorical features
        ('cat_low', 
         OneHotEncoder(handle_unknown='ignore'), 
         ['age_grp', 'sex', 'is_hcp']),
        
        # Handle our complex drug profiles text
        ('drug_profiles_text', 
         TfidfVectorizer(max_features=5000), # Limit to top 5000 drug profiles
         'drug_profile_joined')
    ],
    remainder='drop' # Drop any columns we didn't specify
)

In [15]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y_risk, test_size=0.2, random_state=42)

print(f"\nTraining on {len(X_train)} samples, testing on {len(X_test)} samples.")

Training on 179932 samples, testing on 44984 samples.

In [16]:
from sklearn.multioutput import MultiOutputClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.pipeline import Pipeline



base_classifier = RandomForestClassifier(n_estimators=100, random_state=42, n_jobs=-1)

model_1 = MultiOutputClassifier(base_classifier)

pipeline_risk = Pipeline(steps=[
    ('preprocess', feature_preprocessor),
    ('model', model_1)
])

print("\n--- Starting Model 1 training... ---")
pipeline_risk.fit(X_train, y_train)
print("--- Model 1 Training Complete! ---")

print("\n--- Model 1 Evaluation ---")
y_pred = pipeline_risk.predict(X_test)

--- Starting Model 1 training... ---
--- Model 1 Training Complete! ---

--- Model 1 Evaluation ---

In [17]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

print(f"Subset Accuracy (Strict): {accuracy_score(y_test, y_pred):.4f}")
print(f"F1 Score (Micro): {f1_score(y_test, y_pred, average='micro'):.4f}")
print(f"Recall (Micro): {recall_score(y_test, y_pred, average='micro'):.4f}")
print(f"Precision (Micro): {precision_score(y_test, y_pred, average='micro'):.4f}")

Subset Accuracy (Strict): 0.5106
F1 Score (Micro): 0.6420
Recall (Micro): 0.5909
Precision (Micro): 0.7027

In [18]:
custom_data = {
    'age_grp': 'Adult',
    'sex': 'M',
    'is_hcp': True,            
    'drug_profile_joined': 'ASPIRIN_ROLE_PS_ROUTE_Oral_IND_Headache_DECHAL_Yes'
}

custom_sample = pd.DataFrame(custom_data, index=[0])


prediction_encoded = pipeline_risk.predict(custom_sample)

prediction_labels = mlb_outcomes.inverse_transform(prediction_encoded)   # number to label

print("\n--- Custom Prediction Result ---")
print(f"Predicted Risk Profile: {prediction_labels[0]}")

--- Custom Prediction Result ---
Predicted Risk Profile: ('Other Serious',)

## For reaction model

In [19]:
top_200_reactions = df_basic['reaction_term'].value_counts().head(200).index.tolist()

mlb_reactions = MultiLabelBinarizer(classes=top_200_reactions)

y_reactions = mlb_reactions.fit_transform(df_agg['all_reactions'])

y_reactions

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/preprocessing/_label.py:909: UserWarning: unknown class(es) ["5'nucleotidase increased", '5-hydroxyindolacetic acid in urine increased', '5-hydroxyindolacetic acid increased', '5q minus syndrome', 'ACTH stimulation test abnormal', 'ADAMTS13 activity decreased', 'ADAMTS13 activity increased', 'AST/ALT ratio abnormal', 'Abdominal abscess', 'Abdominal adhesions', 'Abdominal bruit', 'Abdominal cavity drainage', 'Abdominal compartment syndrome', 'Abdominal fat apron', 'Abdominal hernia', 'Abdominal hernia infection', 'Abdominal hernia obstructive', 'Abdominal hernia repair', 'Abdominal incarcerated hernia', 'Abdominal infection', 'Abdominal injury', 'Abdominal lymphadenopathy', 'Abdominal mass', 'Abdominal migraine', 'Abdominal neoplasm', 'Abdominal operation', 'Abdominal pain lower', 'Abdominal rigidity', 'Abdominal sepsis', 'Abdominal strangulated hernia', 'Abdominal symptom', 'Abdominal tenderness', 'Abdominal wall abscess', 'Abdominal wall anomaly', 'Abdominal wall cyst', 'Abdominal wall disorder', 'Abdominal wall haematoma', 'Abdominal wall haemorrhage', 'Abdominal wall oedema', 'Abdominal wall operation', 'Abdominal wall wound', 'Abdominal wound dehiscence', 'Abdominoplasty', 'Abnormal behaviour', 'Abnormal clotting factor', 'Abnormal dreams', 'Abnormal faeces', 'Abnormal labour', 'Abnormal loss of weight', 'Abnormal organ growth', 'Abnormal palmar/plantar creases', 'Abnormal precordial movement', 'Abnormal sensation in eye', 'Abnormal sleep-related event', 'Abnormal weight gain', 'Abortion', 'Abortion early', 'Abortion induced', 'Abortion induced complete', 'Abortion infected', 'Abortion missed', 'Abortion of ectopic pregnancy', 'Abortion spontaneous', 'Abortion threatened', 'Abscess', 'Abscess bacterial', 'Abscess drainage', 'Abscess fungal', 'Abscess intestinal', 'Abscess jaw', 'Abscess limb', 'Abscess neck', 'Abscess of eyelid', 'Abscess of salivary gland', 'Abscess oral', 'Abscess rupture', 'Absence of immediate treatment response', 'Abulia', 'Acanthamoeba infection', 'Acanthoma', 'Acanthosis', 'Acanthosis nigricans', 'Acarodermatitis', 'Accessory renal artery', 'Accessory spleen', 'Accident', 'Accident at home', 'Accident at work', 'Accidental death', 'Accidental exposure to product', 'Accidental exposure to product by child', 'Accidental overdose', 'Accidental poisoning', 'Accidental underdose', 'Accommodation disorder', 'Acetabulum fracture', 'Acetonaemia', 'Achromobacter infection', 'Acid base balance abnormal', 'Acid-base balance disorder mixed', 'Acidosis', 'Acidosis hyperchloraemic', 'Acinetobacter bacteraemia', 'Acinetobacter infection', 'Acinetobacter sepsis', 'Acinetobacter test positive', 'Acne', 'Acne cystic', 'Acne pustular', 'Acoustic neuritis', 'Acoustic neuroma', 'Acoustic stimulation tests abnormal', "Acquired Von Willebrand's disease", 'Acquired amegakaryocytic thrombocytopenia', 'Acquired aminoaciduria', 'Acquired antithrombin III deficiency', 'Acquired apparent mineralocorticoid excess', 'Acquired cardiac septal defect', 'Acquired claw toe', 'Acquired corneal dystrophy', 'Acquired cystic kidney disease', 'Acquired diaphragmatic eventration', 'Acquired gene mutation', 'Acquired haemophilia', 'Acquired immunodeficiency syndrome', 'Acquired mitochondrial DNA mutation', 'Acquired oesophageal web', 'Acquired phimosis', 'Acquired pigmented retinopathy', 'Acquired plagiocephaly', 'Acquired protein S deficiency', 'Acquired tracheo-oesophageal fistula', 'Acral lentiginous melanoma', 'Acral lentiginous melanoma stage II', 'Acral peeling skin syndrome', 'Acrochordon', 'Acromegaly', 'Actinic keratosis', 'Actinomycosis', 'Actinomycotic pulmonary infection', 'Action tremor', 'Activated partial thromboplastin time abnormal', 'Activated partial thromboplastin time prolonged', 'Activated partial thromboplastin time ratio abnormal', 'Activated partial thromboplastin time shortened', 'Activation syndrome', 'Acute HIV infection', 'Acute abdomen', 'Acute cardiac event', 'Acute chest syndrome', 'Acute coronary syndrome', 'Acute cutaneous lupus erythematosus', 'Acute disseminated encephalomyelitis', 'Acute endocarditis', 'Acute erythroid leukaemia', 'Acute febrile neutrophilic dermatosis', 'Acute generalised exanthematous pustulosis', 'Acute graft versus host disease', 'Acute graft versus host disease in intestine', 'Acute graft versus host disease in liver', 'Acute graft versus host disease in skin', 'Acute graft versus host disease oral', 'Acute haemorrhagic ulcerative colitis', 'Acute hepatic failure', 'Acute hepatitis B', 'Acute interstitial pneumonitis', 'Acute left ventricular failure', 'Acute leukaemia', 'Acute lung injury', 'Acute lymphocytic leukaemia', 'Acute lymphocytic leukaemia recurrent', 'Acute macular outer retinopathy', 'Acute monocytic leukaemia', 'Acute motor axonal neuropathy', 'Acute motor-sensory axonal neuropathy', 'Acute myeloid leukaemia', 'Acute myeloid leukaemia (in remission)', 'Acute myeloid leukaemia recurrent', 'Acute myelomonocytic leukaemia', 'Acute myocardial infarction', 'Acute myopia', 'Acute oesophageal mucosal lesion', 'Acute on chronic liver failure', 'Acute phase reaction', 'Acute polyneuropathy', 'Acute postoperative sialadenitis', 'Acute promyelocytic leukaemia', 'Acute psychosis', 'Acute pulmonary histoplasmosis', 'Acute pulmonary oedema', 'Acute respiratory distress syndrome', 'Acute respiratory failure', 'Acute right ventricular failure', 'Acute sinusitis', 'Acute stress disorder', 'Adams-Stokes syndrome', "Addison's disease", 'Adenocarcinoma', 'Adenocarcinoma gastric', 'Adenocarcinoma metastatic', 'Adenocarcinoma of appendix', 'Adenocarcinoma of colon', 'Adenocarcinoma of the cervix', 'Adenocarcinoma pancreas', 'Adenoid cystic carcinoma', 'Adenoidal disorder', 'Adenoidal hypertrophy', 'Adenoidectomy', 'Adenoma benign', 'Adenomatous polyposis coli', 'Adenomyosis', 'Adenotonsillectomy', 'Adenovirus infection', 'Adenovirus reactivation', 'Adhesion', 'Adiposis dolorosa', 'Adjusted calcium decreased', 'Adjusted calcium increased', 'Adjustment disorder', 'Adjustment disorder with anxiety', 'Adjustment disorder with depressed mood', 'Administration related reaction', 'Administration site abscess', 'Administration site bruise', 'Administration site cellulitis', 'Administration site discharge', 'Administration site discolouration', 'Administration site discomfort', 'Administration site erythema', 'Administration site extravasation', 'Administration site haematoma', 'Administration site haemorrhage', 'Administration site hypersensitivity', 'Administration site indentation', 'Administration site induration', 'Administration site infection', 'Administration site inflammation', 'Administration site irritation', 'Administration site joint infection', 'Administration site joint inflammation', 'Administration site nodule', 'Administration site odour', 'Administration site oedema', 'Administration site pain', 'Administration site paraesthesia', 'Administration site phlebitis', 'Administration site pruritus', 'Administration site reaction', 'Administration site streaking', 'Administration site swelling', 'Administration site thrombosis', 'Administration site ulcer', 'Administration site warmth', 'Administration site wound', 'Adnexa uteri cyst', 'Adnexa uteri mass', 'Adnexa uteri pain', 'Adnexal torsion', 'Adrenal adenoma', 'Adrenal androgen deficiency', 'Adrenal cyst', 'Adrenal disorder', 'Adrenal gland cancer', 'Adrenal gland cancer metastatic', 'Adrenal gland injury', 'Adrenal haematoma', 'Adrenal haemorrhage', 'Adrenal insufficiency', 'Adrenal mass', 'Adrenal neoplasm', 'Adrenal suppression', 'Adrenal thrombosis', 'Adrenalitis', 'Adrenocortical carcinoma', 'Adrenocortical insufficiency acute', 'Adrenocorticotropic hormone deficiency', 'Adrenogenital syndrome', 'Adrenomegaly', 'Adult T-cell lymphoma/leukaemia', 'Adult failure to thrive', 'Adulterated product', 'Adverse food reaction', 'Adverse reaction', 'Aeromonas infection', 'Aeromonas test positive', 'Aerophagia', 'Affect lability', 'Affective disorder', 'Age-related macular degeneration', 'Ageusia', 'Aggression', 'Agitated depression', 'Agitation', 'Agitation neonatal', 'Agnosia', 'Agonal death struggle', 'Agoraphobia', 'Agranulocytosis', 'Agraphia', 'Air embolism', 'Airway burns', 'Airway complication of anaesthesia', 'Airway remodelling', 'Akathisia', 'Akinesia', 'Alanine aminotransferase', 'Alanine aminotransferase abnormal', 'Alanine aminotransferase decreased', 'Albumin globulin ratio decreased', 'Albumin globulin ratio increased', 'Albumin urine present', 'Albuminuria', 'Alcohol abuse', 'Alcohol detoxification', 'Alcohol interaction', 'Alcohol intolerance', 'Alcohol poisoning', 'Alcohol problem', 'Alcohol test positive', 'Alcohol use', 'Alcohol use disorder', 'Alcohol withdrawal syndrome', 'Alcoholic', 'Alcoholic hangover', 'Alcoholic ketoacidosis', 'Alcoholic liver disease', 'Alcoholic pancreatitis', 'Alcoholic seizure', 'Alcoholism', 'Aldolase increased', 'Alexia', 'Alice in wonderland syndrome', 'Alkalosis', 'Alkalosis hypochloraemic', 'Allergic bronchitis', 'Allergic colitis', 'Allergic cough', 'Allergic oedema', 'Allergic pharyngitis', 'Allergic reaction to excipient', 'Allergic respiratory disease', 'Allergic respiratory symptom', 'Allergic sinusitis', 'Allergic transfusion reaction', 'Allergy test positive', 'Allergy to animal', 'Allergy to arthropod bite', 'Allergy to arthropod sting', 'Allergy to chemicals', 'Allergy to immunoglobulin therapy', 'Allergy to metals', 'Allergy to plants', 'Allergy to vaccine', 'Allodynia', 'Allogenic stem cell transplantation', 'Alopecia areata', 'Alopecia scarring', 'Alopecia totalis', 'Alopecia universalis', 'Alpha 1 foetoprotein decreased', 'Alpha 1 foetoprotein increased', 'Alpha 1 globulin increased', 'Alpha 1 microglobulin decreased', 'Alpha 1 microglobulin increased', 'Alpha 2 globulin decreased', 'Alpha 2 globulin increased', 'Alpha haemolytic streptococcal infection', 'Alpha-1 antitrypsin deficiency', "Alport's syndrome", 'Altered state of consciousness', 'Altered visual depth perception', 'Alternaria infection', 'Alveolar capillary dysplasia', 'Alveolar lung disease', 'Alveolar osteitis', 'Alveolar proteinosis', 'Alveolar soft part sarcoma', 'Alveolar soft part sarcoma metastatic', 'Alveolitis', 'Amaurosis', 'Amaurosis fugax', 'Amblyopia', 'Ameloblastoma', 'Amenorrhoea', 'American trypanosomiasis', 'Amimia', 'Amino acid level abnormal', 'Amino acid level decreased', 'Amino acid level increased', 'Aminoaciduria', 'Ammonia', 'Ammonia abnormal', 'Ammonia increased', 'Amnesia', 'Amnestic disorder', 'Amniorrhoea', 'Amniotic cavity infection', 'Amniotic fluid index decreased', 'Amniotic fluid volume decreased', 'Amniotic fluid volume increased', 'Amoebiasis', 'Amoebic brain abscess', 'Amoebic colitis', 'Amoebic dysentery', 'Amphetamines', 'Amphetamines negative', 'Amphetamines positive', 'Amputation', 'Amputation stump pain', 'Amputee', 'Amygdalotomy', 'Amylase', 'Amylase abnormal', 'Amylase decreased', 'Amylase increased', 'Amyloidoma', 'Amyloidosis', 'Amyotrophic lateral sclerosis', 'Amyotrophy', 'Anaemia folate deficiency', 'Anaemia macrocytic', 'Anaemia megaloblastic', 'Anaemia neonatal', 'Anaemia of chronic disease', 'Anaemia of malignant disease', 'Anaemia of pregnancy', 'Anaemia postoperative', 'Anaemia vitamin B12 deficiency', 'Anaesthesia', 'Anaesthesia dolorosa', 'Anaesthesia oral', 'Anaesthetic complication', 'Anaesthetic complication cardiac', 'Anaesthetic complication neurological', 'Anal abscess', 'Anal atresia', 'Anal blister', 'Anal cancer', 'Anal cancer stage I', 'Anal cancer stage III', 'Anal dilatation', 'Anal dilation procedure', 'Anal erosion', 'Anal erythema', 'Anal fissure', 'Anal fissure haemorrhage', 'Anal fistula', 'Anal fistula infection', 'Anal haemorrhage', 'Anal hypoaesthesia', 'Anal incontinence', 'Anal infection', 'Anal inflammation', 'Anal injury', 'Anal neoplasm', 'Anal polyp', 'Anal prolapse', 'Anal pruritus', 'Anal rash', 'Anal skin tags', 'Anal sphincter atony', 'Anal sphincter hypertonia', 'Anal squamous cell carcinoma', 'Anal stenosis', 'Anal ulcer', 'Anal ulcer haemorrhage', 'Analgesic drug level above therapeutic', 'Analgesic drug level below therapeutic', 'Analgesic drug level increased', 'Analgesic intervention supportive therapy', 'Anaphylactic reaction', 'Anaphylactic shock', 'Anaphylactic transfusion reaction', 'Anaphylactoid reaction', 'Anaphylactoid shock', 'Anaplastic large-cell lymphoma', 'Anaplastic meningioma', 'Anastomotic complication', 'Anastomotic haemorrhage', 'Anastomotic infection', 'Anastomotic leak', 'Anastomotic stenosis', 'Anastomotic ulcer', 'Anastomotic ulcer haemorrhage', 'Andersen-Tawil syndrome', 'Androgen deficiency', 'Androgen insensitivity syndrome', 'Androgenetic alopecia', 'Androgens increased', 'Anembryonic gestation', 'Aneurysm', 'Aneurysm ruptured', 'Aneurysmal bone cyst', 'Aneurysmectomy', 'Anger', 'Angina bullosa haemorrhagica', 'Angina pectoris', 'Angina unstable', 'Angiocardiogram', 'Angiocentric lymphoma', 'Angiodysplasia', 'Angioedema', 'Angiofibroma', 'Angiogenesis biomarker decreased', 'Angiogram', 'Angiogram abnormal', 'Angiogram peripheral', 'Angiogram peripheral abnormal', 'Angioimmunoblastic T-cell lymphoma', 'Angiokeratoma', 'Angiomyolipoma', 'Angiopathic neuropathy', 'Angiopathy', 'Angioplasty', 'Angiosarcoma', 'Angiotensin converting enzyme increased', 'Angle closure glaucoma', 'Angular cheilitis', 'Anhedonia', 'Animal bite', 'Animal scratch', 'Anion gap abnormal', 'Anion gap decreased', 'Anion gap increased', 'Anisochromia', 'Anisocytosis', 'Anisomastia', 'Ankle arthroplasty', 'Ankle deformity', 'Ankle fracture', 'Ankle operation', 'Ankyloglossia congenital', 'Ankylosing spondylitis', 'Anodontia', 'Anogenital dysplasia', 'Anogenital warts', 'Anonychia', 'Anoplasty', 'Anorectal discomfort', 'Anorectal disorder', 'Anorectal human papilloma virus infection', 'Anorectal infection', 'Anorectal infection bacterial', 'Anorectal operation', 'Anorectal sensory loss', 'Anorectal stenosis', 'Anorectal swelling', 'Anorectal ulcer', 'Anorexia nervosa', 'Anorgasmia', 'Anosmia', 'Anosognosia', 'Anotia', 'Anovulatory cycle', 'Anoxia', 'Anterior chamber cell', 'Anterior chamber degeneration', 'Anterior chamber disorder', 'Anterior chamber fibrin', 'Anterior chamber flare', 'Anterior chamber inflammation', 'Anterior displaced anus', 'Anterior spinal artery syndrome', 'Anterograde amnesia', 'Anti A antibody positive', 'Anti factor VIII antibody positive', 'Anti-GAD antibody positive', 'Anti-HLA antibody test positive', 'Anti-JC virus antibody index', 'Anti-cyclic citrullinated peptide antibody', 'Anti-erythropoietin antibody negative', 'Anti-erythropoietin antibody positive', 'Anti-ganglioside antibody positive', 'Anti-glomerular basement membrane disease', 'Anti-interferon antibody positive', 'Anti-myelin-associated glycoprotein antibodies positive', 'Anti-myelin-associated glycoprotein associated polyneuropathy', 'Anti-neutrophil cytoplasmic antibody positive vasculitis', 'Anti-platelet antibody positive', 'Anti-thyroid antibody positive', 'Antiandrogen therapy', 'Antibiotic level above therapeutic', 'Antibiotic therapy', 'Antibody test abnormal', 'Antibody test negative', 'Antibody test positive', 'Anticholinergic syndrome', 'Anticipatory anxiety', 'Anticoagulant therapy', 'Anticoagulation drug level', 'Anticoagulation drug level abnormal', 'Anticoagulation drug level above therapeutic', 'Anticoagulation drug level below therapeutic', 'Anticoagulation drug level decreased', 'Anticoagulation drug level increased', 'Anticonvulsant drug level abnormal', 'Anticonvulsant drug level above therapeutic', 'Anticonvulsant drug level below therapeutic', 'Anticonvulsant drug level decreased', 'Anticonvulsant drug level increased', 'Antidepressant discontinuation syndrome', 'Antidepressant drug level below therapeutic', 'Antidepressant therapy', 'Antidiuretic hormone abnormality', 'Antimitochondrial antibody positive', 'Antineutrophil cytoplasmic antibody', 'Antineutrophil cytoplasmic antibody decreased', 'Antineutrophil cytoplasmic antibody increased', 'Antineutrophil cytoplasmic antibody positive', 'Antinuclear antibody', 'Antinuclear antibody increased', 'Antinuclear antibody negative', 'Antinuclear antibody positive', 'Antiphospholipid antibodies', 'Antiphospholipid antibodies positive', 'Antiphospholipid syndrome', 'Antipsychotic drug level', 'Antipsychotic drug level above therapeutic', 'Antipsychotic drug level below therapeutic', 'Antipsychotic drug level decreased', 'Antipsychotic drug level increased', 'Antisocial behaviour', 'Antisocial personality disorder', 'Antithyroid arthritis syndrome', 'Antiviral drug level above therapeutic', 'Antiviral drug level below therapeutic', 'Anuria', 'Anxiety disorder', 'Anxiety disorder due to a general medical condition', 'Aortic aneurysm', 'Aortic aneurysm repair', 'Aortic aneurysm rupture', 'Aortic arteriosclerosis', 'Aortic bruit', 'Aortic dilatation', 'Aortic disorder', 'Aortic dissection', 'Aortic dissection rupture', 'Aortic elongation', 'Aortic embolus', 'Aortic intramural haematoma', 'Aortic occlusion', 'Aortic perforation', 'Aortic rupture', 'Aortic stenosis', 'Aortic stent insertion', 'Aortic surgery', 'Aortic thrombosis', 'Aortic valve atresia', 'Aortic valve calcification', 'Aortic valve disease', 'Aortic valve disease mixed', 'Aortic valve incompetence', 'Aortic valve prolapse', 'Aortic valve repair', 'Aortic valve replacement', 'Aortic valve sclerosis', 'Aortic valve stenosis', 'Aortic valve thickening', 'Aortitis', 'Apallic syndrome', 'Apathy', 'Apgar score low', 'Aphakia', 'Aphasia', 'Apheresis', 'Aphonia', 'Aphthous ulcer', 'Apical granuloma', 'Aplasia', 'Aplasia pure red cell', 'Aplastic anaemia', 'Apnoea', 'Apnoea test abnormal', 'Apnoeic attack', 'Apoptosis', 'Apoptotic colonopathy', 'Apparent death', 'Appendiceal abscess', 'Appendicectomy', 'Appendicitis', 'Appendicitis noninfective', 'Appendicitis perforated', 'Appendix cancer', 'Appendix disorder', 'Appetite disorder', 'Application site acne', 'Application site bruise', 'Application site burn', 'Application site calcification', 'Application site coldness', 'Application site discolouration', 'Application site discomfort', 'Application site dryness', 'Application site erosion', 'Application site erythema', 'Application site exfoliation', 'Application site extravasation', 'Application site fibrosis', 'Application site haematoma', 'Application site haemorrhage', 'Application site hypersensitivity', 'Application site induration', 'Application site infection', 'Application site inflammation', 'Application site irritation', 'Application site joint swelling', 'Application site laceration', 'Application site macule', 'Application site mass', 'Application site nodule', 'Application site odour', 'Application site pain', 'Application site papules', 'Application site perspiration', 'Application site pruritus', 'Application site rash', 'Application site reaction', 'Application site scab', 'Application site swelling', 'Application site thrombosis', 'Application site ulcer', 'Application site urticaria', 'Application site vesicles', 'Application site warmth', 'Application site wound', 'Apraxia', 'Aptyalism', 'Aquagenic pruritus', 'Arachnoid cyst', 'Arachnoiditis', 'Arcus lipoides', 'Areflexia', 'Argon plasma coagulation', 'Arm amputation', 'Arnold-Chiari malformation', 'Arrhythmia', 'Arrhythmia supraventricular', 'Arterectomy with graft replacement', 'Arterial bruit', 'Arterial bypass operation', 'Arterial catheterisation', 'Arterial disorder', 'Arterial haemorrhage', 'Arterial injury', 'Arterial insufficiency', 'Arterial ligation', 'Arterial occlusive disease', 'Arterial repair', 'Arterial rupture', 'Arterial spasm', 'Arterial stenosis', 'Arterial stent insertion', 'Arterial therapeutic procedure', 'Arterial thrombosis', 'Arteriosclerosis', 'Arteriosclerosis coronary artery', 'Arteriospasm coronary', 'Arteriovenous fistula',

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 0, 0]], shape=(224916, 200))

In [20]:
X_train, X_test, y_train_reactions, y_test_reactions = train_test_split(
    X, y_reactions, test_size=0.2, random_state=42
)

print(f"\nTraining on {len(X_train)} samples, testing on {len(X_test)} samples.")

Training on 179932 samples, testing on 44984 samples.

In [21]:
base_classifier_2 = RandomForestClassifier(n_estimators=100, random_state=42, n_jobs=-1)

model_2 = MultiOutputClassifier(base_classifier_2)

pipeline_reactions = Pipeline(steps=[
    ('preprocess', feature_preprocessor),
    ('model', model_2)
])

print("\n--- Starting Model 2 (Side Effect Profile) training... ---")
pipeline_reactions.fit(X_train, y_train_reactions)
print("--- Model 2 Training Complete! ---")

--- Starting Model 2 (Side Effect Profile) training... ---
--- Model 2 Training Complete! ---

In [22]:
print("\n--- Model 2 Evaluation ---")
y_pred_reactions = pipeline_reactions.predict(X_test)

print(f"Subset Accuracy (Strict): {accuracy_score(y_test_reactions, y_pred_reactions):.4f}")
print(f"F1 Score (Micro): {f1_score(y_test_reactions, y_pred_reactions, average='micro'):.4f}")
print(f"Recall (Micro): {recall_score(y_test_reactions, y_pred_reactions, average='micro'):.4f}")
print(f"Precision (Micro): {precision_score(y_test_reactions, y_pred_reactions, average='micro'):.4f}")

--- Model 2 Evaluation ---
Subset Accuracy (Strict): 0.2596
F1 Score (Micro): 0.1938
Recall (Micro): 0.1211
Precision (Micro): 0.4845

In [23]:
custom_data = {
    'age_grp': 'Elderly',
    'sex': 'F',
    'is_hcp': False,
    'drug_profile_joined': 'WARFARIN_ROLE_PS_ROUTE_Oral_IND_Atrial fibrillation_DECHAL_No'
}


custom_sample = pd.DataFrame(custom_data, index=[0])

prediction_encoded = pipeline_reactions.predict(custom_sample)
prediction_labels = mlb_reactions.inverse_transform(prediction_encoded)
print("\n--- Custom Prediction Result (Side Effects) ---")
print(f"Predicted Side Effects: {prediction_labels[0]}")

--- Custom Prediction Result (Side Effects) ---
Predicted Side Effects: ()

In [24]:
import joblib

# 1. Save Model 1 (Risk Profile)
print("Saving Risk Model (pipeline_risk)...")
joblib.dump(pipeline_risk, 'risk_model.joblib')

# 2. Save Model 2 (Side Effect Profile)
print("Saving Reactions Model (pipeline_reactions)...")
joblib.dump(pipeline_reactions, 'reactions_model.joblib')

# 3. Save the Risk Binarizer
print("Saving Risk Binarizer (mlb_outcomes)...")
joblib.dump(mlb_outcomes, 'risk_binarizer.joblib')

# 4. Save the Reactions Binarizer
print("Saving Reactions Binarizer (mlb_reactions)...")
joblib.dump(mlb_reactions, 'reactions_binarizer.joblib')

print("\n--- All 4 files saved successfully! ---")

Saving Risk Model (pipeline_risk)...
Saving Reactions Model (pipeline_reactions)...
Saving Risk Binarizer (mlb_outcomes)...
Saving Reactions Binarizer (mlb_reactions)...

--- All 4 files saved successfully! ---